# -*- coding: utf-8 -*-
"""plot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XMtmWRBnPRK5Hz4nd7IaFnRmAi_rCj2f
"""

import matplotlib.pyplot as plt

models = ['LSTM','Bi-LSTM','DAN','RNN','SVM','BERT']
train_accuracies=[0.7707717569786535,0.7694581280788177,0.6351395730706075,0.7310344827586207,0.9775041050903119,0.9129]
validation_accuracies=[0.7294812869336835,0.7189757058437295,0.5902823374917925,0.7452396585686146,0.7977675640183848,0.83]
validation_f1scores=[0.6682769726247988,0.65814696485623,0.42115027829313545,0.6744966442953021,0.7467105263157895,0.83]

plt.rc('figure', figsize=(10, 8))
plt.plot(models,train_accuracies,label='Train Accuracies')
for a,b in zip(models, train_accuracies): 
    plt.text(a, b, str(round(b,3)))
plt.plot(models,validation_accuracies,label='Test Accuracies')
for a,b in zip(models, validation_accuracies): 
    plt.text(a, b, str(round(b,3)))
plt.title("Model Accuracy Scores")
plt.xlabel("Models")
plt.ylabel("Accuracy")
plt.legend()
#plt.savefig('accuracyGraph.jpeg')
plt.show()

plt.savefig('accuracyGraph.jpeg')

plt.rc('figure', figsize=(10, 8))
plt.plot(models,validation_f1scores,label='Test F1 Score',color='orange')
for a,b in zip(models, validation_f1scores): 
    plt.text(a, b, str(round(b,3)))
plt.title("Model F1 Scores")
plt.xlabel("Models")
plt.ylabel("F1")
plt.legend()
#plt.savefig('f1Graph.jpeg')
plt.show()

plt.savefig('f1Graph.jpeg')